[package]
name = "stakbet"
version = "0.1.0"

[[target.starknet-contract]]
sierra = true
casm = true

[dependencies]
starknet = ">=2.2.0"
snforge_std = { git = "https://github.com/foundry-rs/starknet-foundry.git", tag = "v0.10.1" }


